# Site settings
title: gvolpe's blog
description: Principled Software Craftsmanship
baseurl: "/blog"
url: "https://gvolpe.github.io"

author:
  name     : 'Gabriel Volpe'
  url      : https://gvolpe.github.io
  twitter  : https://twitter.com/volpegabriel87

github: https://github.com/gvolpe
disqus_shortname: gvolpe-blog

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
